spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_batch
    username: root
    password: root
  batch:
    initialize-schema: always
    job:
      enabled: true
app:
  datasource:
    url: jdbc:mysql://localhost:3306/app
    username: root
    password: root
  batch:
    initialize-schema: always
    job:
      enabled: true	
  

